linters:
  enable-all: true
  disable:
    - lll
    - interfacer
    - gomnd
    - godox
    - dogsled
    - funlen
    - wsl
  fast: false

issues:
  exclude-rules:
    - path: internal/random/sha.go
      text: "weak cryptographic primitive"
      linters:
        - gosec

run:
  skip-dirs:
    - pkg/client
