linters:
  enable-all: true
  disable:
    - lll
  fast: false

issues:
  exclude-rules:
    - path: internal/testutil/random.go
      text: "weak cryptographic primitive"
      linters:
        - gosec
