linters:
  enable-all: true
  disable:
    - lll
    - interfacer
  fast: false

issues:
  exclude-rules:
    - path: internal/random/sha.go
      text: "weak cryptographic primitive"
      linters:
        - gosec
