project_name: pullup

release:
  github:
    owner: tommy351
    name: pullup

before:
  hooks:
    - go mod download

builds:
  - &build
    id: pullup-controller
    binary: pullup-controller
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/controller
    ldflags:
      - -s -w -X github.com/tommy351/pullup/cmd.Version={{.Version}} -X github.com/tommy351/pullup/cmd.Commit={{.Commit}} -X github.com/tommy351/pullup/cmd.Date={{.Date}}
  - <<: *build
    id: pullup-webhook
    binary: pullup-webhook
    main: ./cmd/webhook

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^test:'

dockers:
  - binaries:
      - pullup-controller
    dockerfile: Dockerfile
    image_templates:
      - 'tommy351/pullup-controller:{{ .Version }}'
      - 'tommy351/pullup-controller:{{ .Major }}.{{ .Minor }}'
      - 'tommy351/pullup-controller:{{ .Major }}'
      - 'tommy351/pullup-controller:latest'
    build_flag_templates:
      - --build-arg=BINARY_NAME=pullup-controller
  - binaries:
      - pullup-webhook
    dockerfile: Dockerfile
    image_templates:
      - 'tommy351/pullup-webhook:{{ .Version }}'
      - 'tommy351/pullup-webhook:{{ .Major }}.{{ .Minor }}'
      - 'tommy351/pullup-webhook:{{ .Major }}'
      - 'tommy351/pullup-webhook:latest'
    build_flag_templates:
      - --build-arg=BINARY_NAME=pullup-webhook
