version: '3.4'

services:
  codegen:
    image: pullup-codegen
    build:
      context: .
      dockerfile: Dockerfile.codegen
    working_dir: /go/src/github.com/tommy351/pullup
    command:
      - bash
      - -c
      - |
        set -euxo pipefail
        /go/src/k8s.io/code-generator/generate-groups.sh all github.com/tommy351/pullup/pkg/client github.com/tommy351/pullup/pkg/apis pullup:v1alpha1 --go-header-file hack/boilerplate.go.txt
        go generate ./...
    volumes:
      - .:/go/src/github.com/tommy351/pullup
