version: '3.4'

services:
  codegen:
    image: pullup-codegen
    build:
      context: .
      dockerfile: Dockerfile.codegen
    working_dir: /go/src/github.com/tommy351/pullup
    command:
      - /go/src/k8s.io/code-generator/generate-groups.sh
      - all
      - github.com/tommy351/pullup/pkg/client
      - github.com/tommy351/pullup/pkg/apis
      - pullup:v1alpha1
    volumes:
      - .:/go/src/github.com/tommy351/pullup
