FROM golang:1.12

RUN go get \
  k8s.io/code-generator/cmd/client-gen \
  k8s.io/code-generator/cmd/deepcopy-gen \
  k8s.io/code-generator/cmd/defaulter-gen \
  k8s.io/code-generator/cmd/lister-gen \
  k8s.io/code-generator/cmd/informer-gen
