// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package resourcetemplate

import (
	"github.com/tommy351/pullup/internal/controller"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

// Injectors from wire.go:

func NewReconciler(mgr manager.Manager) *Reconciler {
	client := controller.NewClient(mgr)
	scheme := controller.NewScheme(mgr)
	eventRecorder := controller.NewEventRecorder(mgr)
	reader := controller.NewAPIReader(mgr)
	reconciler := &Reconciler{
		Client:    client,
		Scheme:    scheme,
		Recorder:  eventRecorder,
		APIReader: reader,
	}
	return reconciler
}
