// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package resourceset

import (
	"github.com/go-logr/logr"
	"github.com/tommy351/pullup/internal/controller"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

// Injectors from wire.go:

func NewReconciler(mgr manager.Manager, logger logr.Logger) *Reconciler {
	client := controller.NewClient(mgr)
	resourcesetLogger := NewLogger(logger)
	eventRecorder := controller.NewEventRecorder(mgr)
	reconciler := &Reconciler{
		Client:   client,
		Logger:   resourcesetLogger,
		Recorder: eventRecorder,
	}
	return reconciler
}
