version: 2.1

commands:
  go_get:
    steps:
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run: go get ./...
      - save_cache:
          paths:
            - /go/pkg/mod
          key: go-mod-{{ checksum "go.sum" }}

jobs:
  lint:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - go_get
      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0
      - run: ./bin/golangci-lint run
      - run: ./hack/verify-codegen.sh
  test_go:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - go_get
      - run: hack/download-test-assets.sh
      - run: hack/run-test.sh
      - store_test_results:
          path: reports/junit
      - run: bash <(curl -s https://codecov.io/bash)
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - go_get
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  main:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test_go:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - lint
            - test_go
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*$/
