version: 2.1

commands:
  go_get:
    steps:
      - restore_cache:
          key: go-pkg
      - run: go get ./...
      - save_cache:
          paths:
            - /go/pkg
          key: go-pkg

jobs:
  lint:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - go_get
      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0
      - run: ./bin/golangci-lint run
  test_go:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - go_get
      - run:
          name: Run tests
          command: go test -v ./...
      - store_test_results:
          path: reports/junit

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test_go
