version: 2.1

commands:
  go_get:
    steps:
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run: go get ./...
      - save_cache:
          paths:
            - /go/pkg/mod
          key: go-mod-{{ checksum "go.sum" }}

executors:
  golang:
    docker:
      - image: circleci/golang:1.15

jobs:
  lint:
    executor: golang
    steps:
      - checkout
      - go_get
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.32.2
      - run: ./bin/golangci-lint run
      - run: ./hack/verify-codegen.sh
  test_go:
    executor: golang
    steps:
      - checkout
      - go_get
      - run: hack/download-test-assets.sh
      - run: hack/run-test.sh
      - store_test_results:
          path: reports/junit
      - run: bash <(curl -s https://codecov.io/bash)
  test_e2e:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Update environment
          command: |
            echo 'export GOROOT=/usr/local/go' >> $BASH_ENV
            echo 'export PATH=$GOROOT/bin:$PATH' >> $BASH_ENV
            sudo ln -s /home/circleci/.go_workspace /go
      - run:
          name: Update to Go 1.15
          working_directory: /tmp
          command: |
            wget https://dl.google.com/go/go1.15.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.15.linux-amd64.tar.gz
      - checkout
      - go_get
      - run: hack/download-test-assets.sh
      - run: test/scripts/build-images.sh
      - run: test/scripts/kind/run.sh
  release:
    executor: golang
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - go_get
      - run: hack/download-test-assets.sh
      - run:
          name: Install git-chglog
          command: |
            mkdir -p $(go env GOPATH)/bin
            curl -L https://github.com/git-chglog/git-chglog/releases/download/0.9.1/git-chglog_linux_amd64 > $(go env GOPATH)/bin/git-chglog
            chmod +x $(go env GOPATH)/bin/git-chglog
      - run:
          name: Generate versioned deployment file
          command: |
            mkdir -p assets/dist
            ./hack/generate-versioned-deployment.sh $(echo $CIRCLE_TAG | sed 's/^v//') > ./assets/dist/pullup-deployment.yml
      - run:
          name: Release
          command: curl -sL https://git.io/goreleaser | bash -s -- --release-notes <(git-chglog $CIRCLE_TAG)

workflows:
  version: 2
  main:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test_go:
          filters:
            tags:
              only: /.*/
      - test_e2e:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - lint
            - test_go
            - test_e2e
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*$/
