// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/tommy351/pullup/cmd"
	"github.com/tommy351/pullup/pkg/controller/resourceset"
	"github.com/tommy351/pullup/pkg/controller/webhook"
	"github.com/tommy351/pullup/pkg/k8s"
	"github.com/tommy351/pullup/pkg/log"
	"github.com/tommy351/pullup/pkg/metrics"
)

// Injectors from wire.go:

func InitializeManager(conf cmd.Config) (*Manager, func(), error) {
	config := cmd.NewKubernetesConfig(conf)
	restConfig, err := k8s.LoadConfig(config)
	if err != nil {
		return nil, nil, err
	}
	scheme, err := k8s.NewScheme()
	if err != nil {
		return nil, nil, err
	}
	manager, err := NewControllerManager(restConfig, scheme, config)
	if err != nil {
		return nil, nil, err
	}
	encoderConfig := log.NewEncoderConfig()
	logConfig := cmd.NewLogConfig(conf)
	atomicLevel, err := log.NewZapLevel(logConfig)
	if err != nil {
		return nil, nil, err
	}
	encoder, err := log.NewEncoder(encoderConfig, atomicLevel)
	if err != nil {
		return nil, nil, err
	}
	writeSyncer, cleanup, err := log.NewSink()
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup2 := log.NewZapLogger(encoder, atomicLevel, writeSyncer)
	logrLogger := log.NewLogger(logger)
	reconciler := resourceset.NewReconciler(manager, logrLogger)
	webhookReconciler := webhook.NewReconciler(manager, logrLogger)
	server := metrics.NewServer(logrLogger)
	mainManager, err := NewManager(manager, reconciler, webhookReconciler, server)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return mainManager, func() {
		cleanup2()
		cleanup()
	}, nil
}
