// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/tommy351/pullup/cmd"
	"github.com/tommy351/pullup/internal/controller"
	"github.com/tommy351/pullup/internal/controller/resourceset"
	"github.com/tommy351/pullup/internal/controller/resourcetemplate"
	"github.com/tommy351/pullup/internal/controller/trigger"
	"github.com/tommy351/pullup/internal/controller/webhook"
	"github.com/tommy351/pullup/internal/k8s"
	"github.com/tommy351/pullup/internal/log"
)

// Injectors from wire.go:

func InitializeManager(conf cmd.Config) (*Manager, func(), error) {
	config := cmd.NewKubernetesConfig(conf)
	restConfig, err := k8s.LoadConfig(config)
	if err != nil {
		return nil, nil, err
	}
	scheme, err := k8s.NewScheme()
	if err != nil {
		return nil, nil, err
	}
	logConfig := cmd.NewLogConfig(conf)
	levelEnabler, err := log.NewZapLevelEnabler(logConfig)
	if err != nil {
		return nil, nil, err
	}
	logger := log.NewLogger(logConfig, levelEnabler)
	manager, err := NewControllerManager(restConfig, scheme, conf, logger)
	if err != nil {
		return nil, nil, err
	}
	client := controller.NewClient(manager)
	eventRecorder := controller.NewEventRecorder(manager)
	reconciler := &resourceset.Reconciler{
		Client:   client,
		Recorder: eventRecorder,
	}
	webhookReconciler := &webhook.Reconciler{
		Client:   client,
		Recorder: eventRecorder,
	}
	reader := controller.NewAPIReader(manager)
	resourcetemplateReconciler := &resourcetemplate.Reconciler{
		Client:    client,
		Scheme:    scheme,
		Recorder:  eventRecorder,
		APIReader: reader,
	}
	reconcilerConfig := trigger.ReconcilerConfig{
		Client:   client,
		Recorder: eventRecorder,
	}
	triggerReconciler, err := trigger.NewReconciler(reconcilerConfig, manager)
	if err != nil {
		return nil, nil, err
	}
	mainManager, err := NewManager(manager, reconciler, webhookReconciler, resourcetemplateReconciler, triggerReconciler)
	if err != nil {
		return nil, nil, err
	}
	return mainManager, func() {
	}, nil
}
