// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package github

import (
	"github.com/tommy351/pullup/internal/controller"
	"github.com/tommy351/pullup/internal/webhook/hookutil"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

// Injectors from wire.go:

func NewHandlerConfig(conf Config, mgr manager.Manager) HandlerConfig {
	client := controller.NewClient(mgr)
	eventRecorder := hookutil.NewEventRecorder(mgr)
	resourceTemplateClient := hookutil.ResourceTemplateClient{
		Client:   client,
		Recorder: eventRecorder,
	}
	handlerConfig := HandlerConfig{
		Config:                 conf,
		Client:                 client,
		Recorder:               eventRecorder,
		ResourceTemplateClient: resourceTemplateClient,
	}
	return handlerConfig
}
