// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package github

import (
	"github.com/tommy351/pullup/internal/controller"
	"github.com/tommy351/pullup/internal/webhook/hookutil"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

// Injectors from wire.go:

func NewHandler(conf Config, mgr manager.Manager) *Handler {
	client := controller.NewClient(mgr)
	eventRecorder := hookutil.NewEventRecorder(mgr)
	fieldIndexer := hookutil.NewFieldIndexer(mgr)
	resourceTemplateClient := hookutil.ResourceTemplateClient{
		Client:   client,
		Recorder: eventRecorder,
	}
	handler := &Handler{
		Config:                 conf,
		Client:                 client,
		Recorder:               eventRecorder,
		Indexer:                fieldIndexer,
		ResourceTemplateClient: resourceTemplateClient,
	}
	return handler
}
