
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pullup
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - pullup.dev
  resources:
  - githubwebhooks
  - webhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pullup.dev
  resources:
  - httpwebhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pullup.dev
  resources:
  - resourcesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - pullup.dev
  resources:
  - resourcetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - pullup.dev
  resources:
  - webhooks
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pullup
  namespace: pullup
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
