---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pullup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pullup
rules:
  # Don't modify pullup.dev group, otherwise the controller may not work.
  - apiGroups:
      - pullup.dev
    resources:
      - webhooks
      - resourcesets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Add resources you want to deploy here
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pullup
subjects:
  - kind: ServiceAccount
    name: pullup
    namespace: default
roleRef:
  kind: ClusterRole
  name: pullup
  apiGroup: rbac.authorization.k8s.io
