---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pullup
  namespace: pullup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pullup
rules:
  - apiGroups:
      - pullup.dev
    resources:
      - webhooks
      - resourcesets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pullup
subjects:
  - kind: ServiceAccount
    name: pullup
    namespace: pullup
roleRef:
  kind: ClusterRole
  name: pullup
  apiGroup: rbac.authorization.k8s.io
