---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pullup
subjects:
  - kind: ServiceAccount
    name: pullup
roleRef:
  kind: ClusterRole
  name: pullup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pullup
subjects:
  - kind: ServiceAccount
    name: pullup
roleRef:
  kind: Role
  name: pullup
  apiGroup: rbac.authorization.k8s.io
