---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pullup
rules:
  - apiGroups:
      - pullup.dev
    resources:
      - webhooks
      - resourcesets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ['']
    resources:
      - events
    verbs:
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pullup
subjects:
  - kind: ServiceAccount
    name: pullup
roleRef:
  kind: ClusterRole
  name: pullup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pullup
rules:
  - apiGroups: ['']
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pullup
subjects:
  - kind: ServiceAccount
    name: pullup
roleRef:
  kind: Role
  name: pullup
  apiGroup: rbac.authorization.k8s.io
