// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package hookutil

import (
	"github.com/tommy351/pullup/internal/controller"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

// Injectors from wire.go:

func NewTriggerHandler(mgr manager.Manager) *TriggerHandler {
	client := controller.NewClient(mgr)
	eventRecorder := NewEventRecorder(mgr)
	triggerHandler := &TriggerHandler{
		Client:   client,
		Recorder: eventRecorder,
	}
	return triggerHandler
}
