// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package trigger

import (
	"github.com/tommy351/pullup/internal/controller"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

// Injectors from wire.go:

func NewReconcilerConfig(mgr manager.Manager) ReconcilerConfig {
	client := controller.NewClient(mgr)
	eventRecorder := controller.NewEventRecorder(mgr)
	reconcilerConfig := ReconcilerConfig{
		Client:   client,
		Recorder: eventRecorder,
	}
	return reconcilerConfig
}
