---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webhooks.pullup.dev
spec:
  group: pullup.dev
  version: v1alpha1
  scope: Namespaced
  names:
    plural: webhooks
    singular: webhook
    kind: Webhook
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            github:
              type: object
              properties:
                secret:
                  type: string
            resources:
              type: array
              minItems: 1
              items:
                type: object
